- name: netology_ml
  hosts: all
  become: yes
  
  vars:
    packages:
      - net-tools
      - git
      - vim
      - tree
      - mc

  tasks:

  - name: Task Ping
    ping:

  - name: Yum Update
    yum:
      update_cache: yes

  - name: Unistall mc
    yum:
      name: mc
      state: absent
  
  - name: Instaling packages
    yum:
      name: "{{packages}}"
      state: latest
 
  - name: Copy file
    copy:
      src: text.txt
      dest: /home/cent
      mode: 0777
  
  - name: Create groups
    group:
      name: "{{item}}"
      state: present
    loop:
      - devops_1
      - test_1

  - name: Create users
    user:
      name: "{{item.client_name}}"
      shell: /bin/bash
      groups: devops_1, test_1
      append: yes
      home: "/home/{{item.home_dir}}"
    with_items:
      - {client_name: devops_1, home_dir: devops_1}
      - {client_name: test_1, home_dir: test_1}
 

